[package]
name = "pho"
version = "0.0.1"
entrypoint = "lib.typ"
authors = ["TycheTellsTales"]
repository = "https://github.com/tychetellstales/typst-pho"
license = "MIT"
description = "A library for automating Worm's Parahuman Online Format."
