name: Typst Test
on:
  push:
    # ensures this is not run for PRs too
    branches: [ main ]
  pull_request:
    # optional but a good default
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Probe runner package cache
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cargo
          version: 1.0

      - name: Install typst-test from github
        uses: baptiste0928/cargo-install@v2.2.0
        with:
          crate: typst-test
          git: https://github.com/tingerrr/typst-test.git
          branch: ci-semi-stable

      - name: Setup typst
        uses: yusancky/setup-typst@v2
        with:
          version: 'v0.10.0'

      - name: Run test suite
        run: typst-test run
